# Generated by Django 6.0.3 on 2026-04-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='street_address',
        ),
        migrations.AddField(
            model_name='address',
            name='building_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='unit_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
