# Generated by Django 6.0.3 on 2026-04-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='address_type',
            field=models.CharField(choices=[('HOUSE', 'House'), ('BUILDING', 'Building')], default='HOUSE', max_length=10),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='building_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='delivery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='unit_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
