# Generated by Django 6.0.3 on 2026-04-28 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaduct', '0002_alter_address_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrefillitem',
            name='jug',
        ),
        migrations.RemoveField(
            model_name='orderrefillitem',
            name='order_item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='generated_jug',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_order_item', to='aquaduct.jug'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('Refill', 'Refill'), ('New Jug', 'New Jug')], default='Refill', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='jug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refill_items', to='aquaduct.jug'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='jug_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_jug_items', to='aquaduct.jugtype'),
        ),
        migrations.DeleteModel(
            name='OrderNewJugItem',
        ),
        migrations.DeleteModel(
            name='OrderRefillItem',
        ),
    ]
