# Generated by Django 6.0.3 on 2026-06-04 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaduct', '0002_jugtype_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='driver_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_no',
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer')], default='Customer', max_length=20),
        ),
    ]
