# Generated by Django 6.0.3 on 2026-06-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquaduct', '0003_remove_driver_role'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='aquaduct_or_driver__cd7d0c_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='driver',
        ),
    ]
