# Generated by Django 6.0.3 on 2026-06-08 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaduct', '0004_remove_order_aquaduct_or_driver__cd7d0c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Order Status Changed', 'Order Status Changed'), ('Jug Type Created', 'Jug Type Created'), ('Jug Type Updated', 'Jug Type Updated'), ('Jug Type Deleted', 'Jug Type Deleted'), ('Customer Deleted', 'Customer Deleted'), ('Customer Created', 'Customer Created'), ('Customer Updated', 'Customer Updated'), ('Login', 'Login'), ('Logout', 'Logout')], max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='aquaduct_ad_timesta_56d0ed_idx'), models.Index(fields=['admin_user', '-timestamp'], name='aquaduct_ad_admin_u_e334d3_idx'), models.Index(fields=['action', '-timestamp'], name='aquaduct_ad_action_bfc3c3_idx')],
            },
        ),
    ]
