# Generated by Django 6.0.3 on 2026-06-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquaduct', '0006_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_notes',
        ),
    ]
