# Generated by Django 6.0.3 on 2026-06-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquaduct', '0007_remove_address_address_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='landmark',
        ),
    ]
