# Generated by Django 6.0.3 on 2026-06-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaduct', '0008_remove_address_landmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address_snapshot',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
