# Generated by Django 6.0.3 on 2026-06-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaduct', '0010_user_failed_login_attempts_user_lockout_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jug',
            name='status',
            field=models.CharField(choices=[('Active', 'ACTIVE'), ('Inactive', 'INACTIVE'), ('Lost', 'LOST'), ('Broken', 'BROKEN')], default='Active', max_length=20),
        ),
    ]
