# Generated by Django 6.0.3 on 2026-06-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaduct', '0011_alter_jug_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jug',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Lost', 'Lost'), ('Broken', 'Broken')], default='Active', max_length=20),
        ),
    ]
