# Generated by Django 6.0.3 on 2026-06-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaduct', '0013_alter_order_status_alter_orderstatushistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('To Be Picked Up', 'To Be Picked Up'), ('Refilling', 'Refilling'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Order Placed', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('To Be Picked Up', 'To Be Picked Up'), ('Refilling', 'Refilling'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
    ]
