# Generated by Django 6.0.3 on 2026-06-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaduct', '0015_alter_order_status_alter_orderstatushistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('Order Status Changed', 'Order Status Changed'), ('Jug Type Created', 'Jug Type Created'), ('Jug Type Updated', 'Jug Type Updated'), ('Jug Type Deleted', 'Jug Type Deleted'), ('Customer Deleted', 'Customer Deleted'), ('Customer Created', 'Customer Created'), ('Customer Updated', 'Customer Updated'), ('Login', 'Login'), ('Logout', 'Logout')], max_length=70),
        ),
    ]
