# Generated by Django 6.0.3 on 2026-06-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaduct', '0016_alter_adminauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refillschedule',
            name='next_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
