# Generated by Django 6.0.3 on 2026-06-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquaduct', '0017_alter_refillschedule_next_reminder_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
