# Generated by Django 6.0.3 on 2026-06-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquaduct', '0018_delete_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JugReport',
        ),
    ]
